/*
 * Knowmad - Knowledge nomad
 * Copyright (C) 2025-2026 LTFan (aka xfqwdsj)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package top.ltfan.knowmad.ui.component

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.text.InlineTextContent
import androidx.compose.foundation.text.appendInlineContent
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.mutableStateSetOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.Layout
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.Placeholder
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.util.fastForEach
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.mikepenz.markdown.compose.LocalMarkdownAnimations
import com.mikepenz.markdown.compose.MarkdownElement
import com.mikepenz.markdown.compose.MarkdownSuccess
import com.mikepenz.markdown.compose.components.MarkdownComponents
import com.mikepenz.markdown.compose.components.markdownComponents
import com.mikepenz.markdown.m3.Markdown
import com.mikepenz.markdown.model.MarkdownState
import com.mikepenz.markdown.model.State
import com.mikepenz.markdown.model.markdownAnnotator
import com.mikepenz.markdown.model.markdownInlineContent
import com.mikepenz.markdown.model.parseMarkdownFlow
import com.mikepenz.markdown.model.rememberMarkdownState
import com.mikepenz.markdown.utils.EntityConverter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.plus
import kotlinx.coroutines.runBlocking
import org.intellij.markdown.ast.ASTNode
import org.intellij.markdown.flavours.gfm.GFMElementTypes

typealias MarkdownSuccessContent = @Composable (
    state: State.Success,
    components: MarkdownComponents,
    modifier: Modifier,
) -> Unit

val DefaultMarkdownSuccessContent: MarkdownSuccessContent = { state, components, modifier ->
    MarkdownSuccess(state = state, components = components, modifier = modifier)
}

const val InlineMathContentIdPrefix = "inline-math-"
const val BlockMathContentIdPrefix = "block-math-"

@Composable
fun MarkdownView(
    state: State,
    modifier: Modifier = Modifier,
    success: MarkdownSuccessContent = DefaultMarkdownSuccessContent,
) {
    val mathIds = remember(state) { mutableStateSetOf<String>() }

    val placeholders = remember(state) { mutableStateMapOf<String, Placeholder>() }
    var placeholdersGenerated by remember(state) { mutableStateOf(false) }

    if (!placeholdersGenerated) {
        Layout(
            contents = mathIds.map { id ->
                {
                    val density = LocalDensity.current
                    KaTeXFromId(
                        id = id,
                        modifier = Modifier.fillMaxWidth(),
                        onSize = { width, height ->
                            placeholders[id] = calculatePlaceHolder(
                                old = placeholders[id],
                                width = width,
                                height = height,
                                density = density,
                            )
                            if (placeholders.size == mathIds.size) {
                                placeholdersGenerated = true
                            }
                        },
                    )
                }
            },
        ) { measurables, constraints ->
            val placeables = measurables.map { it.first().measure(constraints) }
            layout(0, 0) {
                placeables.fastForEach {
                    it.placeRelativeWithLayer(0, 0) { alpha = 0f }
                }
            }
        }
    }

    Markdown(
        state,
        modifier = modifier,
        annotator = markdownAnnotator { content, child ->
            when (child.type) {
                GFMElementTypes.INLINE_MATH -> {
                    val expression =
                        getMathContent(content, child) ?: return@markdownAnnotator false
                    val id = InlineMathContentIdPrefix + expression
                    appendInlineContent(
                        id = id,
                        alternateText = expression,
                    )
                    mathIds += id
                    true
                }

                GFMElementTypes.BLOCK_MATH -> {
                    val expression =
                        getMathContent(content, child) ?: return@markdownAnnotator false
                    val id = BlockMathContentIdPrefix + expression
                    appendInlineContent(
                        id = id,
                        alternateText = expression,
                    )
                    mathIds += id
                    true
                }

                else -> false
            }
        },
        inlineContent = markdownInlineContent(
            placeholders.mapValues { (id, placeholder) ->
                InlineTextContent(placeholder) {
                    val density = LocalDensity.current
                    KaTeXFromId(
                        id = id,
                        modifier = Modifier.fillMaxSize(),
                        onSize = { width, height ->
                            placeholders[id] = calculatePlaceHolder(
                                old = placeholders[id],
                                width = width,
                                height = height,
                                density = density,
                            )
                        },
                    )
                }
            },
        ),
        components = markdownComponents { type, model ->
            when (type) {
                GFMElementTypes.INLINE_MATH -> KaTeX(
                    expression = getMathContent(model.content, model.node)
                        ?: return@markdownComponents,
                    display = false,
                )

                GFMElementTypes.BLOCK_MATH -> KaTeX(
                    expression = getMathContent(model.content, model.node)
                        ?: return@markdownComponents,
                    display = true,
                )
            }
        },
        success = success,
    )
}

@Composable
private fun KaTeXFromId(
    id: String,
    modifier: Modifier = Modifier,
    onSize: (width: Dp, height: Dp) -> Unit = { _, _ -> },
    onError: (String, Throwable?) -> Unit = { _, _ -> },
) {
    val (type, expression) = id.split("-math-", limit = 2)
    when (type) {
        "inline" -> KaTeX(expression, modifier, onSize = onSize, onError = onError)
        "block" -> KaTeX(expression, modifier, display = true, onSize = onSize, onError = onError)
        else -> error("Unknown math content type: $type")
    }
}

private fun getMathContent(fullText: String, node: ASTNode): String? {
    return when (node.type) {
        GFMElementTypes.INLINE_MATH, GFMElementTypes.BLOCK_MATH -> {
            val nodes = node.children.drop(1).dropLast(1)
            if (nodes.isEmpty()) return null
            val escapedContent =
                fullText.subSequence(nodes.first().startOffset, nodes.last().endOffset)
            EntityConverter.replaceEntities(
                escapedContent,
                processEntities = false,
                processEscapes = true,
            ).trimIndent()
        }

        else -> null
    }
}

private fun calculatePlaceHolder(
    old: Placeholder?,
    width: Dp,
    height: Dp,
    density: Density,
): Placeholder {
    with(density) {
        val oldWidth = old?.width ?: 0.sp
        val oldHeight = old?.height ?: 0.sp
        val proposedWidth = width.toSp()
        val proposedHeight = height.toSp()
        val width = if (proposedWidth.value > oldWidth.value) proposedWidth else oldWidth
        val height = if (proposedHeight.value > oldHeight.value) proposedHeight else oldHeight
        return Placeholder(
            width = width,
            height = height,
            placeholderVerticalAlign = Center,
        )
    }
}

@Composable
fun MarkdownView(
    markdown: String,
    modifier: Modifier = Modifier,
    success: MarkdownSuccessContent = DefaultMarkdownSuccessContent,
) {
    val markdownState = rememberMarkdownState(markdown, retainState = true)
    MarkdownView(
        markdownState,
        modifier = modifier,
        success = success,
    )
}

@Composable
fun MarkdownView(
    stateFlow: StateFlow<State>,
    modifier: Modifier = Modifier,
    success: MarkdownSuccessContent = DefaultMarkdownSuccessContent,
) {
    val blockParsing = LocalMarkdownViewBlockParsing.current
    val initialState = remember(blockParsing) {
        if (blockParsing) {
            runBlocking(Dispatchers.Default) { stateFlow.first { it !is State.Loading } }
        } else {
            stateFlow.value
        }
    }

    val state by stateFlow.collectAsStateWithLifecycle(initialState)

    MarkdownView(
        state,
        modifier = modifier,
        success = success,
    )
}

@Composable
fun MarkdownView(
    markdownState: MarkdownState,
    modifier: Modifier = Modifier,
    success: MarkdownSuccessContent = DefaultMarkdownSuccessContent,
) {
    MarkdownView(
        markdownState.state,
        modifier = modifier,
        success = success,
    )
}

@Composable
fun MarkdownView(
    savedMarkdownState: SavedMarkdownState,
    modifier: Modifier = Modifier,
    success: MarkdownSuccessContent = DefaultMarkdownSuccessContent,
) {
    MarkdownView(
        savedMarkdownState.state,
        modifier = modifier,
        success = success,
    )
}

@Composable
fun MarkdownSuccessContentWithTrailingText(
    state: State.Success,
    components: MarkdownComponents,
    modifier: Modifier,
    trailing: String?,
) {
    val animations = LocalMarkdownAnimations.current

    Column(modifier) {
        state.node.children.forEach { node ->
            MarkdownElement(node, components, state.content)
        }
        trailing?.let { trailing ->
            Text(
                trailing,
                modifier = animations.animateTextSize(Modifier),
            )
        }
    }
}

sealed interface SavedMarkdownState {
    val state: StateFlow<State>

    @Immutable
    class Dynamic(
        coroutineScope: CoroutineScope,
        markdownFlow: Flow<String>,
    ) : SavedMarkdownState {
        private val originalState =
            markdownFlow.flatMapLatest { parseMarkdownFlow(it) }.flowOn(Dispatchers.Default)
                .stateIn(
                    coroutineScope + Dispatchers.Default,
                    SharingStarted.Eagerly,
                    State.Loading(),
                )

        override val state = originalState.filter { it !is State.Loading }
            .stateIn(coroutineScope + Dispatchers.Default, SharingStarted.Eagerly, State.Loading())

        suspend fun fixed() = Fixed(originalState.first { it !is State.Loading })
    }

    @Immutable
    class Fixed(state: State) : SavedMarkdownState {
        override val state = MutableStateFlow(state).asStateFlow()
    }

    companion object {
        suspend fun Fixed(markdownText: String): Fixed {
            val state = parseMarkdownFlow(markdownText).flowOn(Dispatchers.Default)
                .first { it !is State.Loading }
            return Fixed(state)
        }
    }
}

fun SavedMarkdownState(
    coroutineScope: CoroutineScope,
    markdownFlow: Flow<String>,
) = SavedMarkdownState.Dynamic(
    coroutineScope,
    markdownFlow,
)

@Composable
fun rememberSavedMarkdownState(markdownFlow: Flow<String>): SavedMarkdownState {
    val coroutineScope = rememberCoroutineScope()
    return remember(coroutineScope, markdownFlow) {
        SavedMarkdownState(coroutineScope, markdownFlow)
    }
}

@Composable
fun rememberSavedMarkdownState(markdownText: String): SavedMarkdownState {
    val coroutineScope = rememberCoroutineScope()

    val flow = remember { MutableStateFlow(markdownText) }

    LaunchedEffect(markdownText) {
        flow.value = markdownText
    }

    return remember(coroutineScope, flow) {
        SavedMarkdownState(coroutineScope, flow)
    }
}

context(viewModel: ViewModel)
fun SavedMarkdownState(markdownFlow: Flow<String>) = SavedMarkdownState(
    viewModel.viewModelScope,
    markdownFlow,
)

val LocalMarkdownViewBlockParsing = staticCompositionLocalOf { false }
