/*
 * Knowmad - Knowledge nomad
 * Copyright (C) 2025 LTFan (aka xfqwdsj)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package top.ltfan.knowmad.ui.viewmodel

import ai.koog.prompt.executor.clients.LLMClient
import ai.koog.prompt.llm.LLMProvider
import ai.koog.prompt.llm.LLModel
import androidx.compose.foundation.text.input.TextFieldState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.Warning
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.navigation3.runtime.NavBackStack
import kotlinx.coroutines.flow.MutableStateFlow
import top.ltfan.knowmad.R
import top.ltfan.knowmad.data.llm.SupportedLLMProviders
import top.ltfan.knowmad.ui.page.WizardMessageItem
import top.ltfan.knowmad.ui.page.WizardSubPage

class WizardPageViewModel(firstPage: WizardSubPage) : ViewModel() {
    val backStack: NavBackStack<WizardSubPage> = NavBackStack(firstPage)

    var cryptoInitializationError by mutableStateOf(false)

    var isUsingPlaintext by mutableStateOf(false)

    private var _apiConfigurationError by mutableStateOf(false)
    var apiConfigurationError: Boolean
        get() = _apiConfigurationError
        set(value) {
            if (value && firstMessageGenerated) {
                return
            }
            _apiConfigurationError = value
        }

    val messageItems
        inline get() = listOf(
            WizardMessageItem(
                icon = Icons.Default.Error,
                message = R.string.crypto_key_initialization_error_message,
            ) to cryptoInitializationError,
            WizardMessageItem(
                icon = Icons.Default.Error,
                message = R.string.llm_message_invalid,
            ) to apiConfigurationError,
            WizardMessageItem(
                icon = Icons.Default.Warning,
                message = R.string.crypto_use_plaintext_warning,
            ) to isUsingPlaintext,
        )

    private var _selectedProvider by mutableStateOf<LLMProvider?>(null)
    var selectedProvider: LLMProvider?
        get() = _selectedProvider
        set(value) {
            if (_selectedProvider != value) {
                _selectedProvider = value
                baseUrl = currentProviderInfo?.defaultBaseUrl ?: ""
                apiKey = ""
                selectedModel = null
                apiConfigurationError = false
            }
        }
    val currentProviderInfo inline get() = SupportedLLMProviders[selectedProvider]

    private var _baseUrl by mutableStateOf("")
    var baseUrl: String
        get() = _baseUrl
        set(value) {
            if (_baseUrl != value) {
                _baseUrl = value
                apiConfigurationError = false
                resetFirstMessage()
            }
        }

    val apiKeyTextFieldState = TextFieldState()

    private var _apiKey by mutableStateOf("")
    var apiKey: String
        get() = _apiKey
        set(value) {
            if (_apiKey != value) {
                _apiKey = value
                apiConfigurationError = false
                resetFirstMessage()
            }
        }

    private var _selectedModel by mutableStateOf<LLModel?>(null)
    var selectedModel: LLModel?
        get() = _selectedModel
        set(value) {
            if (_selectedModel != value) {
                _selectedModel = value
                resetFirstMessage()
            }
        }

    var client: LLMClient? = null

    val firstMessageFlow = MutableStateFlow("")
    var firstMessageGenerationStarted by mutableStateOf(false)
    var firstMessageGenerated by mutableStateOf(false)

    fun resetFirstMessage() {
        firstMessageFlow.value = ""
        firstMessageGenerationStarted = false
        firstMessageGenerated = false
    }
}
