name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set gradlew executable
        run: chmod +x gradlew

      - name: Write signing files
        run: |
          echo ${{ secrets.KEY_FILE }} | base64 --decode > app/key.jks
          echo ${{ secrets.KEY_PROPERTIES }} | base64 --decode > app/key.properties

      - name: Build
        run: |
          ./gradlew assembleRelease

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Knowmad-${{ github.sha }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/outputs/apk/release/Knowmad-${{ github.sha }}.apk
